# Generated by Django 4.1.5 on 2023-01-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serverUrl", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField()),
                ("name", models.CharField(max_length=100, null=True)),
                ("contact_name", models.CharField(max_length=100)),
                ("contactPhone", models.CharField(max_length=30, null=True)),
                ("contactMobile", models.CharField(max_length=30, null=True)),
                ("contactEmail", models.CharField(max_length=100, null=True)),
                ("streetAddress", models.CharField(max_length=100, null=True)),
                ("streetAddress2", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postalCode", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("timezone", models.CharField(max_length=100, null=True)),
                ("locale", models.CharField(max_length=100, null=True)),
                ("shippingSameAsLocation", models.IntegerField(null=True)),
                ("shippingContactName", models.CharField(max_length=100, null=True)),
                ("shippingAddress", models.CharField(max_length=100, null=True)),
                ("shippingAddress2", models.CharField(max_length=100, null=True)),
                ("shippingCity", models.CharField(max_length=100, null=True)),
                ("shippingState", models.CharField(max_length=100, null=True)),
                ("shippingPostalCode", models.CharField(max_length=100, null=True)),
                ("shippingCountry", models.CharField(max_length=100, null=True)),
                ("modified", models.DateTimeField()),
            ],
        ),
    ]
