# Generated by Django 4.1.5 on 2023-01-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="site", old_name="lng", new_name="lon",),
    ]
