# Generated by Django 4.1.5 on 2023-01-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0006_edge_custominfo_edge_recentlinks_edge_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="haLastContact",
            field=models.DateTimeField(null=True),
        ),
    ]
