# Generated by Django 4.1.5 on 2023-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0010_alter_edge_softwareupdated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="deviceId",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
