# Generated by Django 4.1.5 on 2023-01-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "networkanalyzer",
            "0012_alter_edge_edgestatetime_alter_edge_lastcontact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="serialNumber",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
