# Generated by Django 4.1.5 on 2023-01-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0013_alter_edge_serialnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="isSoftwareVersionSupportedByVco",
            field=models.BooleanField(null=True),
        ),
    ]
