# Generated by Django 4.1.5 on 2023-01-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0017_alter_site_postalcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
