# Generated by Django 4.1.5 on 2023-01-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0018_alter_site_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site", name="lat", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="site", name="lon", field=models.FloatField(null=True),
        ),
    ]
