# Generated by Django 4.1.5 on 2023-01-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0019_alter_site_lat_alter_site_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="logicalId",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
