# Generated by Django 4.1.5 on 2023-01-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0022_alter_link_ipv6address"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="bastionState",
            field=models.IntegerField(null=True),
        ),
    ]
