# Generated by Django 4.1.5 on 2023-01-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0023_edge_bastionstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="bastionState",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
