# Generated by Django 4.1.5 on 2023-02-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0026_alter_edge_id_alter_site_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.IntegerField()),
                ("interface_name", models.CharField(max_length=30)),
                ("link_name", models.IntegerField()),
                ("link_mode", models.CharField(max_length=30)),
                ("number_of_interfaces", models.IntegerField()),
            ],
        ),
    ]
