# Generated by Django 4.1.5 on 2023-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0027_database1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.IntegerField()),
                ("interface_name", models.CharField(max_length=30)),
                ("interface_type", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Database3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.IntegerField()),
                ("interface_name", models.CharField(max_length=30)),
                ("event_type", models.IntegerField()),
                ("outage_duration", models.DurationField()),
                ("outage_data", models.JSONField()),
            ],
        ),
    ]
