# Generated by Django 4.1.5 on 2023-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0029_database1_created_at_database2_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database3",
            name="event_type",
            field=models.CharField(max_length=30),
        ),
    ]
