# Generated by Django 4.1.7 on 2023-02-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0033_edge_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="summary",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
