# Generated by Django 4.1.7 on 2023-02-16 00:01

from django.db import migrations
import networkanalyzer.models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0034_edge_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="activationTime",
            field=networkanalyzer.models.ZeroNullDateTime(null=True),
        ),
        migrations.AlterField(
            model_name="edge",
            name="created",
            field=networkanalyzer.models.ZeroNullDateTime(null=True),
        ),
    ]
