# Generated by Django 4.1.7 on 2023-02-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0036_rdsedge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.BigIntegerField(blank=True, null=True)),
                ("site_name", models.BigIntegerField(blank=True, null=True)),
                ("interface_name", models.TextField(blank=True, null=True)),
                ("link_name", models.BigIntegerField(blank=True, null=True)),
                ("link_mode", models.TextField(blank=True, null=True)),
                ("number_of_interfaces", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "devices", "managed": False,},
        ),
    ]
