# Generated by Django 4.1.7 on 2023-02-21 15:32

from django.db import migrations
import networkanalyzer.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "networkanalyzer",
            "0038_alter_edge_activationstate_alter_edge_bastionstate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="lastEvent",
            field=networkanalyzer.models.ZeroNullDateTime(null=True),
        ),
    ]
