# Generated by Django 3.2.18 on 2023-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0040_auto_20230221_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='platformfirmwareversion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
