# Generated by Django 3.2.18 on 2023-02-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0041_edge_platformfirmwareversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='platformbuildnumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
