# Generated by Django 3.2.18 on 2023-02-21 19:21

from django.db import migrations, models
import networkanalyzer.models


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0042_edge_platformbuildnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eventTime', networkanalyzer.models.ZeroNullDateTime()),
                ('event', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=30)),
                ('detail', models.JSONField(null=True)),
                ('enterpriseUserName', models.TextField(null=True)),
                ('edgeName', models.TextField()),
                ('segmentName', models.TextField(null=True)),
            ],
            bases=(models.Model, networkanalyzer.models.JSONReprMixin),
        ),
    ]
