# Generated by Django 3.2.18 on 2023-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0043_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
