# Generated by Django 3.2.18 on 2023-02-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0044_event_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='enterpriseUserName',
            new_name='enterpriseUsername',
        ),
    ]
