# Generated by Django 3.2.18 on 2023-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0045_rename_enterpriseusername_event_enterpriseusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='edgeName',
            field=models.TextField(null=True),
        ),
    ]
