# Generated by Django 3.2.18 on 2023-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkanalyzer', '0046_alter_event_edgename'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edgeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='edgeLogicalId',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enterpriseId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enterpriseLogicalId',
            field=models.TextField(null=True),
        ),
    ]
