# Generated by Django 4.1.7 on 2023-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkanalyzer", "0047_auto_20230221_2004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="edgeId",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
